name: Setup Asdf

description: provisions tooling

# inputs:
#   SetupCommand:
#     description: 'Command to run'
#     required: false
#     default: './setup.bash'

runs:
  using: 'composite'

  steps:
    - uses: extractions/setup-just@v2
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: 'yarn'
