name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# TODO(ioxua): we could maybe replace release-please with `nx release`:
# https://nx.dev/recipes/nx-release/automate-github-releases
jobs:
  Changes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      ChangedProjects: ${{ steps.interrogate.outputs.ChangedProjects }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./setup.sh
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-golang

      - id: interrogate
        uses: ./.github/actions/nx-release-please
        with:
          GithubRepository: ${{ github.repository }}
          GithubToken: ${{ secrets.GITHUB_TOKEN }}
          WorkspaceJsonFilePath: ${{ github.workspace }}/workspace.json

  # Tagging?
  Process:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    needs: Changes

    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.Changes.outputs.ChangedProjects)}}

    name: Process ${{ matrix.package }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: tag-release
        with:
          path: ${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-pull-request: true
          config-file: devops/release-please-config.json
          manifest-file: devops/release-please-manifest.json

      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.releases_created == 'true' }}

  Release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    needs:
      - Changes
      - Process

    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.Changes.outputs.ChangedProjects)}}

    name: Release ${{ matrix.package }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          path: ${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-release: true
          config-file: devops/release-please-config.json
          manifest-file: devops/release-please-manifest.json
