name: Setup Nodejs

description: provisions tooling and installs dependancies

runs:
  using: "composite"

  steps:
    # TODO(ioxua): maybe use setup-node instead of ASDF?

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    #
    # Install things sensitive to the lockfile
    #  - only runs if we had a cache miss from previous step
    - name: install
      shell: bash
      run: corepack yarn install --immutable
